name: mi_card
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=3.4.3"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true
  assets:
     - images/Justin.jpeg
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: Source Sans 3
      fonts:
        - asset: fonts/SourceSans3.ttf

